# Generated by Django 4.2 on 2023-04-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_age_user_gender_user_introduction"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default=False, max_length=100),
        ),
    ]
